[registration]
enabled = false
opens_at = 2026-10-01T12:00:00Z
closes_at = 2026-10-05T23:59:59Z
event = CTF-2026
search_url = http://127.0.0.1:8000
search_url_desc = Splunk Search
scoring_url =
allow_updates = true
scoreboard_app = SA-ctf_scoreboard
users_collection = ctf_users
writer_username = svcaccount
