[general]
writer_username = svcaccount
default_participant_roles = ctf_competitor
allowed_participant_roles = ctf_competitor
default_image_url = /static/app/SA-ctf_registration/images/default-ctf.svg
