[script:ctf_registration]
match = /ctf_registration
script = registration_rest.py
scripttype = persist
handler = registration_rest.RegistrationHandler
requireAuthentication = true
output_modes = json
passPayload = true
passHttpHeaders = true
passHttpCookies = true
python.required = 3.9,3.13
